name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      # set the user so it can run git
      options: --user 1001

    steps:
    - uses: actions/checkout@v4

    - name: Build pdf
      run: make pdf

    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: thesis
        path: build/main.pdf
        if-no-files-found: error
        retention-days: 14
